### ISSUE TITLE
Support for Ruby2.7?

### ISSUE THREAD

**Issue by utkarsh2102** [gfd-dennou-club/ruby-mpi#3]
Hi,

Thank you for your amazing work so far!
However, Ruby2.7 was released in December 2019. Can we have that support with this library, please?

Currently, the build is also failing with Ruby2.5 (with some segfaults) and also with Ruby2.7.
Build logs against 2.5 can be found here: https://launchpadlibrarian.net/464874605/buildlog_ubuntu-focal-amd64.ruby-mpi_0.3.2-2build1_BUILDING.txt.gz

I hope we can switch to 2.7 as quickly as possible :D

**Comment by seiya** [comment]
Hi utkarsh2102,

Your log said that "mpi.h" was not found.

> make[1]: Entering directory '/<<PKGBUILDDIR>>/ext/mpi'
gcc -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -I. -I/usr/include/x86_64-linux-gnu/ruby-2.5.0 -I/usr/include/ruby-2.5.0/ruby/backward -I/usr/include/ruby-2.5.0 -I. -I/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.5.0 -Wdate-time -D_FORTIFY_SOURCE=2   -fPIC -g -O2 -fdebug-prefix-map=/build/ruby2.5-hQITb_/ruby2.5-2.5.7=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC  -o mpi.o -c mpi.c
mpi.c:6:10: fatal error: mpi.h: No such file or directory

I succeeded to compile it with ruby 2.5.5.
Could you try again after installing mpi.h?

**Comment by utkarsh2102** [comment]
How do I install mpi.h? :)

**Comment by seiya** [comment]
MPI (Message Passing Interface) is a protocol for parallel computing.
There are several implementations of the MPI.
The major ones are OpenMP (https://www.open-mpi.org/) and  MPICH (https://www.mpich.org/).
Most OSs, including ubuntu, have their binary packages for them.

Most of the MPI implementations provide a special command to compile MPI applications, e.g., mpicc for C, for users to compile MPI applications without specifying the headers and libraries, such as mpi.h.
If you install a MPI implementation, you should use the mpicc instead of gcc to compile ruby-mpi.

**Comment by utkarsh2102** [comment]
Hi Seiya,

Many thanks for your explanation. It looks like I am able to build with 2.5 :D
However, with 2.7, here's what I get:
```
mpi.c:5:10: fatal error: narray.h: No such file or directory
```

**Comment by seiya** [comment]
Ruby-mpi requires narray (https://masa16.github.io/narray/index.html).
Did you succeed to install it for ruby 2.7?
If so, the extconf.rb failed to find the install path.
You should specify the path of narray.h with the '--with-narray-include=' option for the extconf.rb.

According to your build log for ruby 2.5, the path is '/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.5.0'.
If your install path for ruby 2.7.0 is in the same manner, it may be '/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.7.0'.
It depends on how you install the narray.

**Comment by uwabami** [comment]
Hi, @utkarsh2102 

Please check salsa's our *team* repository: https://salsa.debian.org/ruby-team/ruby-mpi
Close this issue.

Best Wishes,
Youhei
